services:
  transcribe:
    image: huy8895/easy-audio-to-srt-transcribe:cached
    container_name: whisper-openai
    working_dir: /workspace
    environment:
      - FILE
    volumes:
      - .:/workspace
    command: whisper "sample_audio.mp3.mp3" --language en --model tiny --output_format srt --word_timestamps True --max_words_per_line 1 --output_dir /workspace
    platform: linux/amd64