services:
  transcribe:
    build: .
    container_name: whisper-openai
    working_dir: /workspace
    environment:
      - FILE
    volumes:
      - .:/workspace
    command: whisper $FILE --language en --model base --output_format srt --word_timestamps True --max_words_per_line 5 --output_dir /workspace
#    command: whisper $FILE --language en --model base --output_format srt --word_timestamps True --max_words_per_line 10 --output_dir /workspace
  # translate:  # Comment hoặc xóa phần này nếu không cần
  #   build: .
  #   container_name: srt-translator
  #   working_dir: /workspace
  #   environment:
  #     - FILE
  #   volumes:
  #     - .:/workspace
  #   command: python3 translate_srt.py